server:
  port: 8080
  address: 0.0.0.0
spring:
#  profiles:
#    active: local
  security:
    user:
      name: admin
      password: nimda
  application:
    name: eurovision
  datasource:
    url: jdbc:postgresql://yamanote.proxy.rlwy.net:39313/railway
    driver-class-name: "org.postgresql.Driver"
    username: postgres
    password: yFmXZghgzJIDsMKBVtXQbIjGwBkQugJR
  jpa:
    database: postgresql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
    show-sql: false

jwt:
  expiration: 24
  secret: 12345678901234567890123456789012

admin:
  username: admin
  default-password: nimda

countries:
  finalists:
    - "ALBANIA"
    - "ARMENIA"
    - "AUSTRALIA"
    - "AUSTRIA"
    - "AZERBAIJAN"
    - "BELGIUM"
    - "CROATIA"
    - "CYPRUS"
    - "CZECHIA"
    - "DENMARK"
    - "ESTONIA"
    - "FINLAND"
    - "FRANCE"
    - "GEORGIA"
    - "GERMANY"
    - "GREECE"
    - "ICELAND"
    - "IRELAND"
    - "ISRAEL"
    - "ITALY"
    - "LATVIA"
    - "LITHUANIA"
    - "LUXEMBOURG"
    - "MALTA"
    - "MONTENEGRO"
    - "NETHERLANDS"
    - "NORWAY"
    - "POLAND"
    - "PORTUGAL"
    - "SAN_MARINO"
    - "SERBIA"
    - "SLOVENIA"
    - "SPAIN"
    - "SWEDEN"
    - "SWITZERLAND"
    - "UKRAINE"
    - "UNITED_KINGDOM"
  best-food:
    - "ALBANIA"
    - "ARMENIA"
    - "AUSTRALIA"
    - "AUSTRIA"
    - "BELGIUM"
    - "CYPRUS"
    - "CZECHIA"
    - "ESTONIA"
    - "FINLAND"
    - "FRANCE"
    - "GERMANY"
    - "GREECE"
    - "ICELAND"
    - "MALTA"
    - "NETHERLANDS"
    - "POLAND"
    - "PORTUGAL"
    - "SAN_MARINO"
    - "SPAIN"
    - "SWEDEN"
    - "SWITZERLAND"
    - "UNITED_KINGDOM"
  best-guest-outfit:
    - "ALBANIA"
    - "ARMENIA"
    - "AUSTRALIA"
    - "AUSTRIA"
    - "BELGIUM"
    - "CYPRUS"
    - "CZECHIA"
    - "ESTONIA"
    - "FINLAND"
    - "FRANCE"
    - "GERMANY"
    - "GREECE"
    - "ICELAND"
    - "MALTA"
    - "NETHERLANDS"
    - "POLAND"
    - "PORTUGAL"
    - "SAN_MARINO"
    - "SPAIN"
    - "SWEDEN"
    - "SWITZERLAND"
    - "UNITED_KINGDOM"
  bono:
    - "ALBANIA"
    - "ARMENIA"
    - "AUSTRALIA"
    - "AUSTRIA"
    - "AZERBAIJAN"
    - "BELGIUM"
    - "CROATIA"
    - "CYPRUS"
    - "CZECHIA"
    - "ESTONIA"
    - "GERMANY"
    - "ICELAND"
    - "ITALY"
    - "LITHUANIA"
    - "NETHERLANDS"
    - "NORWAY"
    - "PORTUGAL"
    - "SAN_MARINO"
    - "SERBIA"
    - "SLOVENIA"
    - "SWEDEN"
    - "UKRAINE"
  bona:
    - "ALBANIA"
    - "DENMARK"
    - "FINLAND"
    - "FRANCE"
    - "GEORGIA"
    - "GERMANY"
    - "GREECE"
    - "IRELAND"
    - "ISRAEL"
    - "LATVIA"
    - "LITHUANIA"
    - "LUXEMBOURG"
    - "MALTA"
    - "MONTENEGRO"
    - "POLAND"
    - "SPAIN"
    - "SWITZERLAND"
    - "UNITED_KINGDOM"
