server:
  port: 8080
  address: 0.0.0.0
spring:
#  profiles:
#    active: local
  security:
    user:
      name: admin
      password: nimda
  application:
    name: eurovision
  datasource:
    url: jdbc:postgresql://yamanote.proxy.rlwy.net:39313/railway
    driver-class-name: "org.postgresql.Driver"
    username: postgres
    password: yFmXZghgzJIDsMKBVtXQbIjGwBkQugJR
  jpa:
    database: postgresql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: table2062@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  expiration: 24
  secret: 12345678901234567890123456789012

admin:
  username: admin
  default-password: nimda

countries:
  finalists:
    - name: "ALBANIA"
      participant: "Shkodra Elektronike"
    - name: "ARMENIA"
      participant: "PARG"
    - name: "AUSTRALIA"
      participant: "Go-Jo"
    - name: "AUSTRIA"
      participant: "JJ"
    - name: "CZECHIA"
      participant: "ADONXS"
    - name: "DENMARK"
      participant: "Sissal"
    - name: "ESTONIA"
      participant: "Tommy Cash"
    - name: "FINLAND"
      participant: "Erika Vikman"
    - name: "FRANCE"
      participant: "Louane"
    - name: "GEORGIA"
      participant: "Mariam Shengelia"
    - name: "GERMANY"
      participant: "Abor & Tynna"
    - name: "GREECE"
      participant: "Klavdia"
    - name: "ICELAND"
      participant: "VÆB"
    - name: "IRELAND"
      participant: "EMMY"
    - name: "ISRAEL"
      participant: "Yuval Raphael"
    - name: "ITALY"
      participant: "Lucio Corsi"
    - name: "LATVIA"
      participant: "Tautumeitas"
    - name: "LITHUANIA"
      participant: "Katarsis"
    - name: "LUXEMBOURG"
      participant: "Laura Thorn"
    - name: "MALTA"
      participant: "Miriana Conte"
    - name: "MONTENEGRO"
      participant: "Nina Žižić"
    - name: "NETHERLANDS"
      participant: "Claude"
    - name: "NORWAY"
      participant: "Kyle Alessandro"
    - name: "POLAND"
      participant: "Justyna Steczkowska"
    - name: "PORTUGAL"
      participant: "NAPA"
    - name: "SAN_MARINO"
      participant: "Gabry Ponte"
    - name: "SERBIA"
      participant: "Princ"
    - name: "SPAIN"
      participant: "Melody"
    - name: "SWEDEN"
      participant: "KAJ"
    - name: "SWITZERLAND"
      participant: "Zoë Më"
    - name: "UKRAINE"
      participant: "Ziferblat"
    - name: "UNITED_KINGDOM"
      participant: "Remember Monday"
  bono:
    - name: "ALBANIA"
      participant: "Shkodra Elektronike"
    - name: "ARMENIA"
      participant: "PARG"
    - name: "AUSTRALIA"
      participant: "Go-Jo"
    - name: "AUSTRIA"
      participant: "JJ"
    - name: "CZECHIA"
      participant: "ADONXS"
    - name: "ESTONIA"
      participant: "Tommy Cash"
    - name: "GERMANY"
      participant: "Abor & Tynna"
    - name: "ICELAND"
      participant: "VÆB"
    - name: "ITALY"
      participant: "Lucio Corsi"
    - name: "LITHUANIA"
      participant: "Katarsis"
    - name: "NETHERLANDS"
      participant: "Claude"
    - name: "NORWAY"
      participant: "Kyle Alessandro"
    - name: "PORTUGAL"
      participant: "NAPA"
    - name: "SAN_MARINO"
      participant: "Gabry Ponte"
    - name: "SERBIA"
      participant: "Princ"
    - name: "SWEDEN"
      participant: "KAJ"
    - name: "UKRAINE"
      participant: "Ziferblat"
  bona:
    - name: "ALBANIA"
      participant: "Shkodra Elektronike"
    - name: "DENMARK"
      participant: "Sissal"
    - name: "FINLAND"
      participant: "Erika Vikman"
    - name: "FRANCE"
      participant: "Louane"
    - name: "GEORGIA"
      participant: "Mariam Shengelia"
    - name: "GERMANY"
      participant: "Abor & Tynna"
    - name: "GREECE"
      participant: "Klavdia"
    - name: "IRELAND"
      participant: "EMMY"
    - name: "ISRAEL"
      participant: "Yuval Raphael"
    - name: "LATVIA"
      participant: "Tautumeitas"
    - name: "LITHUANIA"
      participant: "Katarsis"
    - name: "LUXEMBOURG"
      participant: "Laura Thorn"
    - name: "MALTA"
      participant: "Miriana Conte"
    - name: "MONTENEGRO"
      participant: "Nina Žižić"
    - name: "POLAND"
      participant: "Justyna Steczkowska"
    - name: "SPAIN"
      participant: "Melody"
    - name: "SWITZERLAND"
      participant: "Zoë Më"
    - name: "UNITED_KINGDOM"
      participant: "Remember Monday"
  best-food:
    - name: "ALBANIA"
    - name: "ARMENIA"
    - name: "AUSTRALIA"
    - name: "AUSTRIA"
    - name: "BELGIUM"
    - name: "CYPRUS"
    - name: "CZECHIA"
    - name: "ESTONIA"
    - name: "FINLAND"
    - name: "FRANCE"
    - name: "GERMANY"
    - name: "GREECE"
    - name: "ICELAND"
    - name: "MALTA"
    - name: "NETHERLANDS"
    - name: "POLAND"
    - name: "PORTUGAL"
    - name: "SAN_MARINO"
    - name: "SPAIN"
    - name: "SWEDEN"
    - name: "SWITZERLAND"
    - name: "UNITED_KINGDOM"
  best-guest-outfit:
    - name: "BELGIUM"
    - name: "FRANCE"
    - name: "GREECE"
    - name: "ICELAND"
    - name: "MALTA"
    - name: "SPAIN"
    - name: "SWEDEN"
    - name: "UNITED_KINGDOM"